/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VENTANAS;
import EDD.Grafo;
import EXTRAS.Funciones;
import JSON.LecturaJSON;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class EDITOR_DATA extends javax.swing.JFrame {
    static Grafo grafo;
    static LecturaJSON json;
    static Funciones funciones;
    /**
     * Creates new form MENU_SIGUIENTE
     */
    public EDITOR_DATA(Grafo grafo,LecturaJSON json) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.grafo=grafo;
        this.json=json;
        funciones = new Funciones();
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/ICONO.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AGREGAR_LINEA = new javax.swing.JButton();
        INPUT_LINEA = new javax.swing.JTextField();
        CERRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        INPUT_ESTACIONES = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        REGRESAR = new javax.swing.JButton();
        INSTRUCCIONES = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDITOR DE DATA");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVA LINEA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDITOR DATA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ESTACIONES:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        AGREGAR_LINEA.setBackground(new java.awt.Color(0, 51, 51));
        AGREGAR_LINEA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AGREGAR_LINEA.setForeground(new java.awt.Color(255, 255, 255));
        AGREGAR_LINEA.setText("AGREGAR LINEA");
        AGREGAR_LINEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_LINEAActionPerformed(evt);
            }
        });
        getContentPane().add(AGREGAR_LINEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        INPUT_LINEA.setBackground(new java.awt.Color(0, 0, 51));
        INPUT_LINEA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INPUT_LINEA.setForeground(new java.awt.Color(255, 255, 255));
        INPUT_LINEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUT_LINEAActionPerformed(evt);
            }
        });
        getContentPane().add(INPUT_LINEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 280, -1));

        CERRAR.setBackground(new java.awt.Color(255, 0, 0));
        CERRAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CERRAR.setForeground(new java.awt.Color(255, 255, 255));
        CERRAR.setText("X");
        CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRARActionPerformed(evt);
            }
        });
        getContentPane().add(CERRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        INPUT_ESTACIONES.setBackground(new java.awt.Color(0, 0, 51));
        INPUT_ESTACIONES.setColumns(20);
        INPUT_ESTACIONES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INPUT_ESTACIONES.setForeground(new java.awt.Color(255, 255, 255));
        INPUT_ESTACIONES.setRows(5);
        jScrollPane1.setViewportView(INPUT_ESTACIONES);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 280, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/METRO.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 100));

        REGRESAR.setBackground(new java.awt.Color(0, 51, 51));
        REGRESAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        REGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        REGRESAR.setText("REGRESAR");
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(REGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        INSTRUCCIONES.setBackground(new java.awt.Color(0, 51, 51));
        INSTRUCCIONES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INSTRUCCIONES.setForeground(new java.awt.Color(255, 255, 255));
        INSTRUCCIONES.setText("INSTRUCCIONES");
        INSTRUCCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSTRUCCIONESActionPerformed(evt);
            }
        });
        getContentPane().add(INSTRUCCIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FONDO_AZUL.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INPUT_LINEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUT_LINEAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INPUT_LINEAActionPerformed

    private void CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRARActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CERRARActionPerformed

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
        MENU_PRINCIPAL MP = new MENU_PRINCIPAL(grafo, json);
        MP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_REGRESARActionPerformed

    private void AGREGAR_LINEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_LINEAActionPerformed
        try{
            String linea = INPUT_LINEA.getText();
            String estaciones = INPUT_ESTACIONES.getText();
            if (!linea.isBlank()){
                if (!estaciones.isBlank()){
                    String[] estacionesnuevas = estaciones.split("\n");
                    funciones.agregarLinea(estacionesnuevas, linea, grafo, json);
                }
                else {
                JOptionPane.showMessageDialog(this, "Debe ingresar las estaciones 🚄️");
            }
            }
            else {
                JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la linea 🗒️");
            }
            INPUT_LINEA.setText("");
            INPUT_ESTACIONES.setText("");
        }catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado!!!");
        }       
    }//GEN-LAST:event_AGREGAR_LINEAActionPerformed

    private void INSTRUCCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSTRUCCIONESActionPerformed
        JOptionPane.showMessageDialog(this, "Instrucciones Editor Data\n" 
                                          + "Al ingresar los datos hagalo con la siguiente estrucutura:\n"
                                          + "Nombre de Linea \n"
                                          + "Estación nueva 1\n" +
                                            "Estación nueva 2\n" +
                                            "Estación nueva 3\n" +
                                            "Estación nueva 4-Estación existente\n" +
                                            "Estación nueva 5\n" +
                                            "Estación nueva N\n"
                                          + "Es necesario agregar al menos una conexion peatonal\n"
                                          + "Por ejemplo: Estacion nueva 4-Plaza Venezuela\n"
                                          + "Al finalizar, haga click en el boton AGREGAR LINEA para guardar los datos en la red de transporte");
    }//GEN-LAST:event_INSTRUCCIONESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDITOR_DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDITOR_DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDITOR_DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDITOR_DATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDITOR_DATA(grafo, json).setVisible(true);
            }
            
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR_LINEA;
    private javax.swing.JButton CERRAR;
    private javax.swing.JLabel FONDO;
    private javax.swing.JTextArea INPUT_ESTACIONES;
    private javax.swing.JTextField INPUT_LINEA;
    private javax.swing.JButton INSTRUCCIONES;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
